# Generated by Django 2.1.1 on 2018-09-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='uid',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
    ]
