# Generated by Django 2.1.1 on 2018-09-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0002_auto_20180908_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('time', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='pw',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
    ]
