# Generated by Django 2.1.1 on 2018-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0003_auto_20180909_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiazzaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
            ],
        ),
    ]
