# Generated by Django 2.1.1 on 2018-09-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0005_remove_festadata_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festadata',
            name='image',
        ),
    ]
